#!/usr/bin/env bash
# Transfers a file within the server..
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.

if [ $# -lt 4 ]
then
  echo "Usage: ./transfer  0-setup_web_static.sh 54.173.210.14 ubuntu ~/.ssh/school"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
